giftcardreaderfix: giftcardreader.c
		gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 hang.gft
				


giftcardexamplewriter:
		gcc -o giftcardexamplewriter giftcardexamplewriter.c && ./giftcardexamplewriter
