giftcardreaderfix: giftcardreaderfixed.c
		gcc -o giftcardreader giftcardreader.c && ./giftcardreader 1 crash2.gft


giftcardexamplewriter:
		gcc -o giftcardexamplewriter giftcardexamplewriter.c && ./giftcardexamplewriter
